development:
  adapter: postgresql
  encoding: unicode
  database: warehouse_development
  user: postgres
  password: postgres
  host: bd
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: warehouse_test
  user: postgres
  password: postgres
  host: bd
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: warehouse_production
  pool: 5
